spring.application.name=backend
server.port=8080

# Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Tracing sampler
management.tracing.sampling.probability=1.0

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
