spring.application.name=backend-test
server.port=0

spring.data.mongodb.uri=mongodb://localhost:27017/aura_test

jwt.secret=test-secret-key-123456
jwt.expiration=3600000

management.tracing.enabled=false
management.zipkin.tracing.endpoint=
management.endpoints.web.exposure.include=health